# Generated by Django 4.2.3 on 2023-07-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
    ]
